{
 "title": "00 AD Services v1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ALL DC Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "AD DS Performance" },
     "functions": [
      {
       "$$hashKey": "object:111",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ALL DC CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "AD DS Performance" },
     "functions": [
      {
       "$$hashKey": "object:84",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "Active Directory All Services",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "Services" },
     "functions": [
      {
       "$$hashKey": "object:1258",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": State of service ",
        "  | "
       ],
       "text": "replaceAlias(: State of service ,   | )"
      },
      {
       "$$hashKey": "object:1259",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "Microsoft Exchange",
        " "
       ],
       "text": "replaceAlias(Microsoft Exchange,  )"
      },
      {
       "$$hashKey": "object:1260",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      },
      {
       "$$hashKey": "object:1261",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTFLY-",
        " "
       ],
       "text": "replaceAlias(ISTFLY-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/service/" },
     "itemTag": { "filter": "Application: AD DS Services" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Domain Controller Servers Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "application": { "filter": "General" },
     "functions": [
      {
       "$$hashKey": "object:1229",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": Uptime",
        " "
       ],
       "text": "replaceAlias(: Uptime,  )"
      },
      {
       "$$hashKey": "object:1230",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DC Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "Application: /.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 0,
      "count": true,
      "minSeverity": 0
     }
    }
   ]
  },
  {
   "title": "Space utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:557",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "(C:): Space utilization" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:578",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Domain Controllers" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "DATA(D:): Space utilization" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "NTLM Authentications",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:308",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "NTLM Authentications" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LDAP Client Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:32",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "LDAP Client Sessions" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Kerberos Authentications",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:389",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Kerberos Authentications" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LDAP Searches/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:637",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "LDAP Searches/sec" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LSASS Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:443",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "LSASS Processor Time" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LSASS Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:470",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "LSASS Processor Time" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Q",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:503",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "Active Directory" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/.Disk average queue/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "$$hashKey": "object:524",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "ISTMSK-",
        " "
       ],
       "text": "replaceAlias(ISTMSK-,  )"
      }
     ],
     "group": { "filter": "01 Domain Controllers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Average disk write queue length"
     },
     "itemTag": { "filter": "Application: Performance" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}